#!/usr/bin/python3
import sys
from primes import factors

if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    with open(sys.argv[1], 'r') as file:
        for line in file:
            i = int(line.strip())
            j = factors(i)
            print(f"{i}={i//j}*{j}")
